version: "3.9"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/pleaseletmein
      - NEO4J_PLUGINS=["apoc"]
    networks:
      - cognee_backend

  cognee:
    networks:
      - cognee_backend
    build:
      context: ./
    volumes:
      - "./:/app"
      - ./.data:/app/.data
    environment:
      - HOST=0.0.0.0
      - ENVIRONMENT=local
    profiles: ["exclude-from-up"]
    ports:
      - 8000:8000
      - 443:443
      - 80:80
      - 50051:50051
    depends_on:
      - postgres
      - neo4j
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8GB
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=bla
      - POSTGRES_PASSWORD=bla
      - POSTGRES_DB=bubu
    networks:
      - cognee_backend
    ports:
      - "5432:5432"
networks:
  cognee_backend:
    name: cognee_backend

