[tool.poetry]
name = "cognee"
version = "0.1.0"
description = "Cognee cognitive architecture is a library for enriching LLM context with a semantic layer"
authors = ["Vasilije Markovic"]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/topoteretes/cognee"
repository = "https://www.cognee.ai"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Software Development :: Libraries",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",]

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.0.338"

openai = "1.3.3"
python-dotenv = "1.0.0"
fastapi = "0.104.1"
uvicorn = "0.22.0"
boto3 = "^1.26.125"
gunicorn = "^20.1.0"
weaviate-client = "4.4b1"
sqlalchemy = "^2.0.21"
asyncpg = "^0.28.0"
instructor = "^0.3.4"
networkx = "^3.2.1"
graphviz = "^0.20.1"
neo4j = "^5.14.1"
langdetect = "^1.0.9"
iso639 = "^0.1.4"
debugpy = "^1.8.0"
lancedb = "^0.5.5"
pyarrow = "^15.0.0"
pylint = "^3.0.3"
qdrant-client = "^1.7.3"
aiosqlite = "^0.20.0"
pymupdf = "^1.23.25"
pandas = "^2.2.1"
greenlet = "^3.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
