name: Python Linting

on:
  push:
    branches: [ main ]  # This will trigger the workflow on pushes to the main branch
  pull_request:  # This will trigger the workflow on any pull request to any branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint  # Install pylint

    - name: Run pylint
      run: |
        pylint $(git ls-files '*.py')  # Run pylint on all Python files in the repository
